#=====================================
#
# NKD - A simple Jekyll boilerplate
#
# More on Jekyll: http://jekyllrb.com/
#
#=====================================

# This will be the first part of the title tag for your site
# <title> {{site.name}} </title>
# ============================================================
name: "Detroit Head Start"

# Populates the meta description for the site. Should be under 150 characters for best SEO results.
# ============================================================
description: "Get free pre-school and child care in Detroit! Head Start serves families with kids from birth to 5 years old. Find a Detroit location near you."

# Change this to your production URL
# ============================================================
url: http://headstart.theworkdept.com

# Publish future posts or not option.
# ============================================================
future: true

# "A list of directories (including trailing slash) and files to exclude from the conversion"
# I normally exclude _sass, README*, and .gitignore
# Directories that start with an underscore _ are not copied over by default. Still like to include _sass anyways.
# ============================================================
exclude: [README.md, Rakefile, node_modules]

# Pagination variable for how many posts to show in a list
# ============================================================
#paginate: 5

# Style of permalinks
# ============================================================
permalink: pretty

# Variable format options for URL styles below
# ============================================================
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-:day-:year/:title.html/                 => 04-29-2009/slap-chop.html
# /blog/:year/:month/:day/:title                  => /blog/2009/04/29/slap-chop/index.html

# Uncomment if you have pygments installed. Used for code syntax highlighting.
# If you're not doing syntax highlighting you can delete this.
# highlighter: pygments
